# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leland Barton
email: public@lelandbarton.com
description: Personal Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lelandbarton.com" # the base hostname & protocol for your site
twitter_username: lelandbarton
github_username:  lelandbarton
stackoverflow_username:  bartonleland

# Build settings
markdown: kramdown


